### ISSUE TITLE
Backendmodeller

### ISSUE THREAD

**Issue by Joel80** [virtuella-team/vteam-sds#16]
I översiktsbilden över alla komponenter har vi en komponent mellan api och databas som bara kallas "backend". I introduktionen skriver vi att denna komponent sköter kommunikationen mellan databas och api men inte så mycket mer om detta sedan tror jag. Tänker att vi antingen borde ta bort den biten eller skriva något mer om den. I min tankevärld är komponenten "backend" i den bilden närmast ett modellager (iaf såspom vi har använt begreppet "modell" i kurserna webbapp och  jsramverk). Jag tänker att de modellerna ansvarar för att skicka  sql-frågor till databasen men också att de ansvarar för att göra beräkningar ofta med stöd av geodatabibliotek (men här kanske de beräkningarna ska göras på annat håll ibland, t.ex. i cykeln eller i frontend?) Jag har ett förslag på text att lägga in mellan avsnitten databas och api i dokumentet:

### Backendmodeller
I backend ingår ett lager med modeller som sköter kommunikationen mellan api och databas, alltså skickar in SQL-frågor till databasen och tar emot svar. I dessa modeller genomförs också olika beräkningar. Det kan tex handla om att beräkna kostnaden för en resa, eller beräkna om en cykel befinner sig inom en viss zon. För att göra de nödvändiga geografiska beräkningarna använder vi oss av geodatabibliotek som underlättar detta. Efter att ha undersökt olika bibliotek både för Python och JS kom vi fram till att JS biblioteken tycks vara mer lättanvända.[X] Vi kommer därför använda oss av TurfJS, ett bibliotek som som har flera funktioner som kommer att underlätta för oss att beräkna cyklarnas positioner och göra backendmodellerna effektivare.[X] [Y]

[X] "Hantering av geodata i databas/backend". Internet: https://github.com/virtuella-team/vteam-sds/blob/main/8_teknisk_analys_geo/teknisk_analys_geo.md [2022-11-19].
[Y] "Turf.js". Internet: https://turfjs.org/ [2022-11-19]. 

Och att vi sedan i linje med detta skriver i introduktionen:
"Backendmodeller - en komponent som sköter kommunikationen mellan API och databas och genomför beräkningar"
Samt ändrar i bilden så att det står Backendmodeller istället för Backend

**Comment by patrikmalvenius** [comment]
dunder tycker jag! ta du och ändra sådär!

**Comment by tomas-zw** [comment]
Har uppdaterad SDS'n med backendmodeller nu
