### ISSUE TITLE
Lägga till information om Leaflet och varför vi väljer det

### ISSUE THREAD

**Issue by Joel80** [virtuella-team/vteam-sds#18]
Jag funderar på om vi ska lägga till lite kort info om Leaflet, vad det är och varför vi väljer det i frontendavsnitttet där det nämns under admingränssnitt. Kanske så här:

Leaflet är ett JavaScript bibliotek för att hantera interaktiva kartor. Bibliotekeket fungerar väl både för desktop och mobil och är därför ett bra val för att hantera kartor i ett system som innehåller applikationer för båda dessa typer av enheter.[X]

[X] "Leaflet - a JavaScript library for interactive maps". Internet: https://leafletjs.com/ [2022-11-19]

Fråga: bör Leaflet nämnas på andra ställen också under frontendavsnitten?

**Comment by patrikmalvenius** [comment]
jag tar den bollen! hmm jo leaflet bör ju nämnas överallt där det används, jag ser till att det är med
