### ISSUE TITLE
Ändra forbiddenZone till  zone i API-routeslistan

### ISSUE THREAD

**Issue by Joel80** [virtuella-team/vteam-sds#19]
Ska vi byta forbiddenZone till zone i listan över routes? Min tanke är att en "zone" kan vara förbjuden eller t.ex. hastighetsbegränsad och att samma route kan användas för att hämta ut info om zonen. Vet inte om det är riktigt resonerat

**Comment by sonnerberg** [comment]
Låter vettigt. Jag tar denna senare om ingen annan hinner före.
