### ISSUE TITLE
Verkstadstabellen i databasen

### ISSUE THREAD

**Issue by Joel80** [virtuella-team/vteam-sds#20]
Tabellen verkstad har ett frågetecken efter sig i databasbilden. Jag satte nog dit det i min bild för att jag var osäker på entiteten skulle vara med. Hur tänker vi här ska den vara med eller inte?

**Comment by tomas-zw** [comment]
Jag har nog tänkt att den ska vara med, sen hur vi använder den är en annan femma.  Hålla det enkelt är mitt förslag. Ett id och adress och bara koppla en cykel till verkstad om den är på service. Vill man ha alla cyklar på service så blir det en query till cykeltabellen.

**Comment by tomas-zw** [comment]
vill vi ändra på det sen med relation åt båda hållen så går ju det att göra utan att behöva ändra API't.

**Comment by Joel80** [comment]
Ok låter vettigt tycker jag.

**Comment by Joel80** [comment]
Ta bort frågetecknet i bilden

**Comment by Joel80** [comment]
Har gjort en merge och stänger denna
