### ISSUE TITLE
Koppling laddstation cykel i databasen

### ISSUE THREAD

**Issue by Joel80** [virtuella-team/vteam-sds#21]
En sak jag är osäker på är hur vi kopplar cyklar till laddstationer. Ska det vara en relation som vi lägger till i databasen? Så att vi kan se vilka cyklar en laddstation (för närvarande) har. Eller löser vi det på annat sätt?

**Comment by tomas-zw** [comment]
Här tänker jag att göra samma som för en verkstad, Hålla det enkelt med bara id o adress.

**Comment by Joel80** [comment]
Ok låter vettigt tycker jag.
