### ISSUE TITLE
Realistiska användare i simuleringen

### ISSUE THREAD

**Issue by Joel80** [virtuella-team/vteam-sds#22]
Jag tänker att en extra feature som vi har pratat en del om är att de simulerade användarna ska bete sig realistiskt (dvs. typ köra på väg isället för vatten). Om vi vill satsa på det kanske vi ska lägga till några ord under avsnittet simulering. Jag tänker:

"Simuleringsprogrammet  kommer att använda sig av geodata för att simulera  ett realistiskt användarbeteende. "

Eller nåt sånt...

**Comment by patrikmalvenius** [comment]
jag tar den bollen!
