### ISSUE TITLE
Not till den tekniska studien om backend och databaser

### ISSUE THREAD

**Issue by Joel80** [virtuella-team/vteam-sds#23]
Tycker det vore bra att lägga till en not till studien om databaser i avsnittet där vi beskriver varför vi valt den vi har. Kanske så här (vet inte riktigt hur man notar till ett repo):

[X] "Requests/sek". Internet: https://github.com/virtuella-team/vteam/tree/tzLocal [2022-11-19]

**Comment by tomas-zw** [comment]
Vi nämner att vi baserar vårat val på ett test, så sjävklart bör den vara med.
Fixar det!

**Comment by tomas-zw** [comment]
fixat
