### ISSUE TITLE
Uppdatera innehållsförteckningen

### ISSUE THREAD

**Issue by patrikmalvenius** [virtuella-team/vteam-sds#25]
När allt annat är klart....den är i osynk redan nu

**Comment by sonnerberg** [comment]
Har uppdaterat via PR, men detta behöver så klart göras igen.

**Comment by sonnerberg** [comment]
Denna kan stängas efter merge #41

**Comment by Joel80** [comment]
Har gjort en merge av #41 och stänger denna
