### ISSUE TITLE
Backend-delen inte klar i main?

### ISSUE THREAD

**Issue by patrikmalvenius** [virtuella-team/vteam-sds#27]
Noterar att det finns en överstruken URI och en not om TODO i backend-delen i main just nu, antar det är work in progress?

**Comment by tomas-zw** [comment]
TODO'n är helt enkelt att jag inte vet hur/var vi får geodata

**Comment by patrikmalvenius** [comment]
Ah. I mitt huvud hämtar vi bakgrundskartor + vägnät från Open Street Map, all annan data (hur långt varje stad sträcker sig, parkeringsplatser, laddstationer etc) genereras av administratörerna

**Comment by tomas-zw** [comment]
Lysande! lägger till det.

**Comment by sonnerberg** [comment]
Jag strök URI för jag tror att URL är rätt beteckning. Vad säger ni?

**Comment by patrikmalvenius** [comment]
Tummen upp
