### ISSUE TITLE
API-delen inte klar i main?

### ISSUE THREAD

**Issue by patrikmalvenius** [virtuella-team/vteam-sds#29]
Noterar att det står så här:

Dokumentation

För att underlätta för tredjepartsleverntörer att bygga externa tjänster och applicationer är REST-API’et väldokumenterat.

    Länk till dokumentationen?
    Ett exempel från dokumentationen på en enskild endpoint?

För min del kan det räcka med den första meningen, alltså strunta i exempel på dokumentation?

**Comment by tomas-zw** [comment]
Joel och jag pratade lite om det idag, och för tillfället så finns det ingen sån dokumentation. Och är lite tveksam att vi har ett komplett API doc till fre. Men att skapa doc för en route och länka till en WIP kan funka.

**Comment by sonnerberg** [comment]
Jag lägger en stund på att undersöka hur det kan göras i Postman.

**Comment by sonnerberg** [comment]
Efter att ha tittat runt lite på Postman så skulle jag säga att det är ett lovande verktyg, men att man nog får läsa på / kolla video för att komma igång med att skapa API-dokumentation genom Postman. 

Man kan samarbeta i ett workspace mellan konton om man vill.

**Comment by Joel80** [comment]
Vi går på Patriks förslag
